apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quanos
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quanos
      app.kubernetes.io/component: api
