apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quanos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/limit-rps: '20'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - quanos.example.com
      secretName: quanos-tls
  rules:
    - host: quanos.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quanos
                port:
                  number: 80
