apiVersion: v1
kind: Secret
metadata:
  name: quanos-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017
  JWT_SECRET: dev-secret-of-at-least-32-chars-long-please-replace
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: change-me-please-after-first-boot
