#values below are intentioally invalid placeholders. Not to deploy as is
apiVersion: v1
kind: Secret
metadata:
  name: quanos-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017
  JWT_SECRET: REPLACE_ME_BEFORE_DEPLOY_REPLACE_ME_BEFORE_DEPLOY_REPLACE_ME_BEFORE_DEPLOY
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: REPLACE_ME
